Added macro to run our unit tests.
I'd like our build server to run our unit tests so when a project builds,
we then run the tests before we create the packages. If the tests fail,
then we have to go back to them to make them pass. This should force me
to better keep the code up to date.

Fixed the error detecting the BUILD and dist directories in the mk script.

diff --git a/scripts/mk b/scripts/mk
--- a/scripts/mk
+++ b/scripts/mk
@@ -298,11 +298,18 @@ OUTPUT="${BUILD}/${TYPE}/${CONTRIBDIR}${PROJECT}"
 PROJECT_TMPDIR="${OUTPUT}/tmp"
 
 BINARY_DIR="`cd ${OUTPUT} && pwd`"
-DIST_DIR="`cd ${BUILD}/${TYPE}/dist && pwd`"
 RESULT=${?}
 if [[ ${RESULT} != 0 ]]
 then
     echo "error: could not cd to OUTPUT directory \"${OUTPUT}\"."
+    exit 1
+fi
+
+DIST_DIR="`cd ${BUILD}/${TYPE}/dist && pwd`"
+RESULT=${?}
+if [[ ${RESULT} != 0 ]]
+then
+    echo "error: could not cd to DIST directory \"${BUILD}/${TYPE}/dist\"."
     exit 1
 fi
 
